const GET_MOVIES='GET_MOVIES';
const SEARCH_MOVIES='SEARCH_MOVIES';
const GET_MOVIE_BY_ID='GET_MOVIE_BY_ID';
const GET_MOVIE_BY_GENRE='GET_MOVIE_BY_GENRE';
const GET_GENRES='GET_GENRES';

export {GET_MOVIES , GET_MOVIE_BY_ID,SEARCH_MOVIES,GET_GENRES,GET_MOVIE_BY_GENRE}